from langchain_community.document_loaders import DirectoryLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_ollama import OllamaEmbeddings
from langchain_chroma import Chroma
from langchain_ollama import ChatOllama
from langchain_classic.chains import create_retrieval_chain
from langchain_classic.chains.combine_documents import create_stuff_documents_chain
from langchain_core.prompts import ChatPromptTemplate

# 1. Load the SFU Data
print("Loading data...")
loader = DirectoryLoader('./sfu_data', glob="**/*.txt")
documents = loader.load()

# 2. Split the text
print("Splitting text...")
text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)
chunks = text_splitter.split_documents(documents)

# 3. Create the Database
print("Creating database...")
embeddings = OllamaEmbeddings(model="nomic-embed-text")
vector_store = Chroma.from_documents(chunks, embeddings, persist_directory="./chroma_db")

# 4. Connect to your local Llama 3.1
print("Connecting to Llama...")
llm = ChatOllama(model="llama3.1")

# 5. Create the QA Chain with Guardrails & Disclaimer
system_prompt = (
    "You are the official SFU SIAT Course Planning AI Assistant.\n"
    "Your sole task is to assist Simon Fraser University students with course selection, degree requirements, prerequisites, and academic regulations based STRICTLY on the provided context.\n\n"
    "STRICT GUARDRAILS:\n"
    "1. Grounding: Answer the question using ONLY the provided context below. Do NOT use outside knowledge or assumptions about SFU policies not listed in the text.\n"
    "2. Missing Info: If the answer cannot be determined from the context, explicitly state: 'I do not have enough information in the official SFU dataset to answer this question accurately.'\n"
    "3. Irrelevant Queries: If a user asks a question unrelated to SFU, SIAT, or academic course planning (e.g., general chat, coding help, games, weather), politely decline by stating: 'I can only assist with SFU course planning and academic degree queries.'\n"
    "4. Course Load & Repeats: Pay strict attention to limits regarding credit caps (18 units max per term without overload) and course repeat policies (maximum 1 repeat per course, max 5 total repeats).\n"
    "5. Advisor Disclaimer: ALWAYS end your response with the following exact disclaimer on a new line:\n"
    "\"\\n---\\n*Disclaimer: This response is generated by an AI assistant for planning purposes only. Please verify all requirements with an official SFU Academic Advisor or the current SFU Academic Calendar.*\"\n\n"
    "Context:\n{context}"
)

prompt = ChatPromptTemplate.from_messages([
    ("system", system_prompt),
    ("human", "{input}"),
])

question_answer_chain = create_stuff_documents_chain(llm, prompt)
qa_chain = create_retrieval_chain(vector_store.as_retriever(search_kwargs={"k": 4}), question_answer_chain)

# 6. Run the Evaluation Test!
print("\n--- Model Response ---")
query = "I want to take IAT 265. I have completed IAT 167 with a A, but I failed MATH 130. Can I take it?"
response = qa_chain.invoke({"input": query})
print(response['answer'])