import os
from langchain_community.document_loaders import DirectoryLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_ollama import OllamaEmbeddings
from langchain_chroma import Chroma
from langchain_ollama import ChatOllama
from langchain_classic.chains import create_retrieval_chain, create_history_aware_retriever
from langchain_classic.chains.combine_documents import create_stuff_documents_chain
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.messages import HumanMessage, AIMessage


# Runs Terminal version unless web version is running (used for Streamlit web app)
def main(web_mode=False):
    # 1. Database Initialization
    db_dir = "./chroma_db"
    data_dir = "./sfu_data"
    embeddings = OllamaEmbeddings(model="nomic-embed-text")

    if os.path.exists(db_dir) and os.listdir(db_dir):
        print("Loading existing Chroma database...")
        vector_store = Chroma(persist_directory=db_dir, embedding_function=embeddings)
    else:
        print("Building database from SFU data files...")
        loader = DirectoryLoader(data_dir, glob="**/*.txt")
        documents = loader.load()
        text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)
        chunks = text_splitter.split_documents(documents)
        vector_store = Chroma.from_documents(chunks, embeddings, persist_directory=db_dir)

    # Connect to Llama 3.1
    print("Connecting to Llama 3.1 model...")
    llm = ChatOllama(model="llama3.1")

    # Create the History-Aware Retriever
    contextualize_q_system_prompt = (
        "Given a chat history and the latest user question "
        "which might reference context in the chat history, "
        "formulate a standalone question which can be understood "
        "without the chat history. Do NOT answer the question, "
        "just reformulate it if needed and otherwise return it as is."
    )
    contextualize_q_prompt = ChatPromptTemplate.from_messages([
        ("system", contextualize_q_system_prompt),
        MessagesPlaceholder("chat_history"),
        ("human", "{input}"),
    ])

    history_aware_retriever = create_history_aware_retriever(
        llm, vector_store.as_retriever(search_kwargs={"k": 4}), contextualize_q_prompt
    )

    # Define System Prompt with Strict Guardrails & Disclaimer
    system_prompt = (
        "You are the official SFU SIAT Course Planning AI Assistant.\n"
        "Your task is to actively assist SFU students with course selection, degree requirements, prerequisites, and academic regulations based STRICTLY on the provided context.\n\n"
        "INTERACTIVE GUIDANCE & GUARDRAILS:\n"
        "1. Interactive Clarification: If a student asks if they can take a course but hasn't provided their grades/course history, state the exact prerequisites from the context and ASK them clarifying follow-up questions (e.g., 'Have you completed CMPT 120 with a C- or higher?') so you can help them determine their eligibility together.\n"
        "2. Grounding: Rely ONLY on the provided context. Do NOT fabricate SFU rules.\n"
        "3. Irrelevant Queries: Decline non-SFU academic queries politely.\n"
        "4. Advisor Disclaimer: ALWAYS end your final answer with:\n"
        "\"\\n---\\n*Disclaimer: This response is generated by an AI assistant for planning purposes only. Please verify all requirements with an official SFU Academic Advisor or the current SFU Academic Calendar.*\"\n\n"
        "Context:\n{context}"
    )

    prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        MessagesPlaceholder(variable_name="chat_history"),
        ("human", "{input}"),
    ])

    # Final Chain
    question_answer_chain = create_stuff_documents_chain(llm, prompt)
    qa_chain = create_retrieval_chain(history_aware_retriever, question_answer_chain)

    # If Streamlit is using the chatbot, return the RAG chain and skip the terminal interface
    if web_mode:
        return qa_chain

    # Interactive Welcome Banner & Capabilities
    print("\n" + "=" * 60)
    print(" 🎓 WELCOME TO THE SFU SIAT COURSE PLANNING ASSISTANT 🎓 ")
    print("=" * 60)
    print("Hello! I am your AI academic assistant for the School of Interactive")
    print("Arts and Technology (SIAT). Here is what I can help you with:")
    print("  • Lower & Upper-Division IAT Course Prerequisites")
    print("  • Required Math/CMPT Prerequisites (MATH 130, MACM 101, CMPT 120)")
    print("  • SIAT BA & BSc Degree Requirements & GPA Thresholds")
    print("  • SFU Credit Limits & Term Overload Regulations")
    print("  • Course Repeat Policies & WQB Graduation Rules")
    print("-" * 60)
    print("Type your academic query below, or type 'exit' or 'quit' to end session.")
    print("=" * 60 + "\n")

    # Chat history buffer
    chat_history = []

    # Interactive Prompt Loop
    while True:
        try:
            query = input("\n[Student Query] > ")
        except (KeyboardInterrupt, EOFError):
            print("\nExiting course planner. Good luck with your studies!")
            break

        if query.strip().lower() in ["exit", "quit"]:
            print("\nThank you for using the SFU SIAT Course Planning Assistant. Goodbye!")
            break

        if not query.strip():
            continue

        print("\nThinking...")
        
        # Pass conversation history along with user query
        response = qa_chain.invoke({
            "input": query,
            "chat_history": chat_history
        })

        answer = response['answer']
        print("\n--- Assistant Response ---")
        print(answer)

        # Print the source documents used for the answer
        print("\n[Sources Referenced]:")
        sources = set([doc.metadata.get('source', 'Unknown File') for doc in response['context']])
        if not sources:
             print("- No direct sources cited.")
        for source in sources:
            print(f"- {source}")

        # Save conversation turn into history
        chat_history.append(HumanMessage(content=query))
        chat_history.append(AIMessage(content=answer))

if __name__ == "__main__":
    main()